// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: metrics.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntervalSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collector string `protobuf:"bytes,1,opt,name=collector,proto3" json:"collector,omitempty"`
	// Types that are assignable to Value:
	//	*IntervalSummary_Number
	//	*IntervalSummary_NumberValues
	//	*IntervalSummary_Point
	//	*IntervalSummary_PointValues
	Value isIntervalSummary_Value `protobuf_oneof:"value"`
}

func (x *IntervalSummary) Reset() {
	*x = IntervalSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metrics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntervalSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntervalSummary) ProtoMessage() {}

func (x *IntervalSummary) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntervalSummary.ProtoReflect.Descriptor instead.
func (*IntervalSummary) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *IntervalSummary) GetCollector() string {
	if x != nil {
		return x.Collector
	}
	return ""
}

func (m *IntervalSummary) GetValue() isIntervalSummary_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *IntervalSummary) GetNumber() *SummaryInteger {
	if x, ok := x.GetValue().(*IntervalSummary_Number); ok {
		return x.Number
	}
	return nil
}

func (x *IntervalSummary) GetNumberValues() *SummaryIntegerSlice {
	if x, ok := x.GetValue().(*IntervalSummary_NumberValues); ok {
		return x.NumberValues
	}
	return nil
}

func (x *IntervalSummary) GetPoint() *SummaryDouble {
	if x, ok := x.GetValue().(*IntervalSummary_Point); ok {
		return x.Point
	}
	return nil
}

func (x *IntervalSummary) GetPointValues() *SummaryDoubleSlice {
	if x, ok := x.GetValue().(*IntervalSummary_PointValues); ok {
		return x.PointValues
	}
	return nil
}

type isIntervalSummary_Value interface {
	isIntervalSummary_Value()
}

type IntervalSummary_Number struct {
	Number *SummaryInteger `protobuf:"bytes,2,opt,name=number,proto3,oneof"`
}

type IntervalSummary_NumberValues struct {
	NumberValues *SummaryIntegerSlice `protobuf:"bytes,3,opt,name=number_values,json=numberValues,proto3,oneof"`
}

type IntervalSummary_Point struct {
	Point *SummaryDouble `protobuf:"bytes,4,opt,name=point,proto3,oneof"`
}

type IntervalSummary_PointValues struct {
	PointValues *SummaryDoubleSlice `protobuf:"bytes,5,opt,name=point_values,json=pointValues,proto3,oneof"`
}

func (*IntervalSummary_Number) isIntervalSummary_Value() {}

func (*IntervalSummary_NumberValues) isIntervalSummary_Value() {}

func (*IntervalSummary_Point) isIntervalSummary_Value() {}

func (*IntervalSummary_PointValues) isIntervalSummary_Value() {}

type SummaryIntegerSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value []int64 `protobuf:"varint,2,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *SummaryIntegerSlice) Reset() {
	*x = SummaryIntegerSlice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metrics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummaryIntegerSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryIntegerSlice) ProtoMessage() {}

func (x *SummaryIntegerSlice) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryIntegerSlice.ProtoReflect.Descriptor instead.
func (*SummaryIntegerSlice) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *SummaryIntegerSlice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SummaryIntegerSlice) GetValue() []int64 {
	if x != nil {
		return x.Value
	}
	return nil
}

type SummaryInteger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SummaryInteger) Reset() {
	*x = SummaryInteger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metrics_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummaryInteger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryInteger) ProtoMessage() {}

func (x *SummaryInteger) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryInteger.ProtoReflect.Descriptor instead.
func (*SummaryInteger) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *SummaryInteger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SummaryInteger) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SummaryDoubleSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value []float64 `protobuf:"fixed64,2,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *SummaryDoubleSlice) Reset() {
	*x = SummaryDoubleSlice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metrics_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummaryDoubleSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryDoubleSlice) ProtoMessage() {}

func (x *SummaryDoubleSlice) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryDoubleSlice.ProtoReflect.Descriptor instead.
func (*SummaryDoubleSlice) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *SummaryDoubleSlice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SummaryDoubleSlice) GetValue() []float64 {
	if x != nil {
		return x.Value
	}
	return nil
}

type SummaryDouble struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SummaryDouble) Reset() {
	*x = SummaryDouble{}
	if protoimpl.UnsafeEnabled {
		mi := &file_metrics_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SummaryDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryDouble) ProtoMessage() {}

func (x *SummaryDouble) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryDouble.ProtoReflect.Descriptor instead.
func (*SummaryDouble) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *SummaryDouble) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SummaryDouble) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_metrics_proto protoreflect.FileDescriptor

var file_metrics_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x1a, 0x0c, 0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x02, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x30, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72,
	0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x0d, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x48, 0x00, 0x52,
	0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x2d, 0x0a,
	0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x44, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x0c,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x48, 0x00,
	0x52, 0x0b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x07, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3f, 0x0a, 0x13, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3a, 0x0a, 0x0e, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x3e, 0x0a, 0x12, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x44, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x39, 0x0a, 0x0d, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x44, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xc0,
	0x02, 0x0a, 0x16, 0x50, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x40, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x15, 0x2e, 0x70,
	0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x1a, 0x16, 0x2e, 0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e, 0x50, 0x6f, 0x70,
	0x6c, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0e, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x10, 0x2e,
	0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e, 0x50, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x49, 0x44, 0x1a,
	0x16, 0x2e, 0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e, 0x50, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e,
	0x50, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x70, 0x6f, 0x70, 0x6c, 0x61,
	0x72, 0x2e, 0x50, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x37, 0x0a, 0x0b, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12,
	0x10, 0x2e, 0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e, 0x50, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x49,
	0x44, 0x1a, 0x16, 0x2e, 0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e, 0x50, 0x6f, 0x70, 0x6c, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x03, 0x41, 0x64, 0x64,
	0x12, 0x17, 0x2e, 0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x1a, 0x16, 0x2e, 0x70, 0x6f, 0x70, 0x6c,
	0x61, 0x72, 0x2e, 0x50, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData = file_metrics_proto_rawDesc
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(file_metrics_proto_rawDescData)
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_metrics_proto_goTypes = []interface{}{
	(*IntervalSummary)(nil),     // 0: poplar.IntervalSummary
	(*SummaryIntegerSlice)(nil), // 1: poplar.SummaryIntegerSlice
	(*SummaryInteger)(nil),      // 2: poplar.SummaryInteger
	(*SummaryDoubleSlice)(nil),  // 3: poplar.SummaryDoubleSlice
	(*SummaryDouble)(nil),       // 4: poplar.SummaryDouble
	(*CreateOptions)(nil),       // 5: poplar.CreateOptions
	(*PoplarID)(nil),            // 6: poplar.PoplarID
	(*PoplarResponse)(nil),      // 7: poplar.PoplarResponse
}
var file_metrics_proto_depIdxs = []int32{
	2, // 0: poplar.IntervalSummary.number:type_name -> poplar.SummaryInteger
	1, // 1: poplar.IntervalSummary.number_values:type_name -> poplar.SummaryIntegerSlice
	4, // 2: poplar.IntervalSummary.point:type_name -> poplar.SummaryDouble
	3, // 3: poplar.IntervalSummary.point_values:type_name -> poplar.SummaryDoubleSlice
	5, // 4: poplar.PoplarMetricsCollector.CreateCollector:input_type -> poplar.CreateOptions
	6, // 5: poplar.PoplarMetricsCollector.CloseCollector:input_type -> poplar.PoplarID
	6, // 6: poplar.PoplarMetricsCollector.ResetSample:input_type -> poplar.PoplarID
	6, // 7: poplar.PoplarMetricsCollector.FlushSample:input_type -> poplar.PoplarID
	0, // 8: poplar.PoplarMetricsCollector.Add:input_type -> poplar.IntervalSummary
	7, // 9: poplar.PoplarMetricsCollector.CreateCollector:output_type -> poplar.PoplarResponse
	7, // 10: poplar.PoplarMetricsCollector.CloseCollector:output_type -> poplar.PoplarResponse
	7, // 11: poplar.PoplarMetricsCollector.ResetSample:output_type -> poplar.PoplarResponse
	7, // 12: poplar.PoplarMetricsCollector.FlushSample:output_type -> poplar.PoplarResponse
	7, // 13: poplar.PoplarMetricsCollector.Add:output_type -> poplar.PoplarResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	file_poplar_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_metrics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntervalSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metrics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummaryIntegerSlice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metrics_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummaryInteger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metrics_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummaryDoubleSlice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_metrics_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SummaryDouble); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_metrics_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*IntervalSummary_Number)(nil),
		(*IntervalSummary_NumberValues)(nil),
		(*IntervalSummary_Point)(nil),
		(*IntervalSummary_PointValues)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_metrics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_rawDesc = nil
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
