// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: poplar.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOptions_RecorderType int32

const (
	CreateOptions_UNKNOWN_RECORDER       CreateOptions_RecorderType = 0
	CreateOptions_PERF                   CreateOptions_RecorderType = 1
	CreateOptions_PERF_SINGLE            CreateOptions_RecorderType = 2
	CreateOptions_PERF_100MS             CreateOptions_RecorderType = 3
	CreateOptions_PERF_1S                CreateOptions_RecorderType = 4
	CreateOptions_HISTOGRAM_SINGLE       CreateOptions_RecorderType = 6
	CreateOptions_HISTOGRAM_100MS        CreateOptions_RecorderType = 7
	CreateOptions_HISTOGRAM_1S           CreateOptions_RecorderType = 8
	CreateOptions_INTERVAL_SUMMARIZATION CreateOptions_RecorderType = 9
)

// Enum value maps for CreateOptions_RecorderType.
var (
	CreateOptions_RecorderType_name = map[int32]string{
		0: "UNKNOWN_RECORDER",
		1: "PERF",
		2: "PERF_SINGLE",
		3: "PERF_100MS",
		4: "PERF_1S",
		6: "HISTOGRAM_SINGLE",
		7: "HISTOGRAM_100MS",
		8: "HISTOGRAM_1S",
		9: "INTERVAL_SUMMARIZATION",
	}
	CreateOptions_RecorderType_value = map[string]int32{
		"UNKNOWN_RECORDER":       0,
		"PERF":                   1,
		"PERF_SINGLE":            2,
		"PERF_100MS":             3,
		"PERF_1S":                4,
		"HISTOGRAM_SINGLE":       6,
		"HISTOGRAM_100MS":        7,
		"HISTOGRAM_1S":           8,
		"INTERVAL_SUMMARIZATION": 9,
	}
)

func (x CreateOptions_RecorderType) Enum() *CreateOptions_RecorderType {
	p := new(CreateOptions_RecorderType)
	*p = x
	return p
}

func (x CreateOptions_RecorderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateOptions_RecorderType) Descriptor() protoreflect.EnumDescriptor {
	return file_poplar_proto_enumTypes[0].Descriptor()
}

func (CreateOptions_RecorderType) Type() protoreflect.EnumType {
	return &file_poplar_proto_enumTypes[0]
}

func (x CreateOptions_RecorderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateOptions_RecorderType.Descriptor instead.
func (CreateOptions_RecorderType) EnumDescriptor() ([]byte, []int) {
	return file_poplar_proto_rawDescGZIP(), []int{1, 0}
}

type CreateOptions_EventsCollectorType int32

const (
	CreateOptions_UNKNOWN_COLLECTOR CreateOptions_EventsCollectorType = 0
	CreateOptions_BASIC             CreateOptions_EventsCollectorType = 1
	CreateOptions_PASSTHROUGH       CreateOptions_EventsCollectorType = 2
	CreateOptions_SAMPLING_100      CreateOptions_EventsCollectorType = 3
	CreateOptions_SAMPLING_1K       CreateOptions_EventsCollectorType = 4
	CreateOptions_SAMPLING_10K      CreateOptions_EventsCollectorType = 5
	CreateOptions_SAMPLING_100K     CreateOptions_EventsCollectorType = 6
	CreateOptions_RAND_SAMPLING_50  CreateOptions_EventsCollectorType = 7
	CreateOptions_RAND_SAMPLING_25  CreateOptions_EventsCollectorType = 8
	CreateOptions_RAND_SAMPLING_10  CreateOptions_EventsCollectorType = 9
	CreateOptions_INTERVAL_100MS    CreateOptions_EventsCollectorType = 10
	CreateOptions_INTERVAL_1S       CreateOptions_EventsCollectorType = 11
)

// Enum value maps for CreateOptions_EventsCollectorType.
var (
	CreateOptions_EventsCollectorType_name = map[int32]string{
		0:  "UNKNOWN_COLLECTOR",
		1:  "BASIC",
		2:  "PASSTHROUGH",
		3:  "SAMPLING_100",
		4:  "SAMPLING_1K",
		5:  "SAMPLING_10K",
		6:  "SAMPLING_100K",
		7:  "RAND_SAMPLING_50",
		8:  "RAND_SAMPLING_25",
		9:  "RAND_SAMPLING_10",
		10: "INTERVAL_100MS",
		11: "INTERVAL_1S",
	}
	CreateOptions_EventsCollectorType_value = map[string]int32{
		"UNKNOWN_COLLECTOR": 0,
		"BASIC":             1,
		"PASSTHROUGH":       2,
		"SAMPLING_100":      3,
		"SAMPLING_1K":       4,
		"SAMPLING_10K":      5,
		"SAMPLING_100K":     6,
		"RAND_SAMPLING_50":  7,
		"RAND_SAMPLING_25":  8,
		"RAND_SAMPLING_10":  9,
		"INTERVAL_100MS":    10,
		"INTERVAL_1S":       11,
	}
)

func (x CreateOptions_EventsCollectorType) Enum() *CreateOptions_EventsCollectorType {
	p := new(CreateOptions_EventsCollectorType)
	*p = x
	return p
}

func (x CreateOptions_EventsCollectorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateOptions_EventsCollectorType) Descriptor() protoreflect.EnumDescriptor {
	return file_poplar_proto_enumTypes[1].Descriptor()
}

func (CreateOptions_EventsCollectorType) Type() protoreflect.EnumType {
	return &file_poplar_proto_enumTypes[1]
}

func (x CreateOptions_EventsCollectorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateOptions_EventsCollectorType.Descriptor instead.
func (CreateOptions_EventsCollectorType) EnumDescriptor() ([]byte, []int) {
	return file_poplar_proto_rawDescGZIP(), []int{1, 1}
}

type PoplarID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PoplarID) Reset() {
	*x = PoplarID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poplar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoplarID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoplarID) ProtoMessage() {}

func (x *PoplarID) ProtoReflect() protoreflect.Message {
	mi := &file_poplar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoplarID.ProtoReflect.Descriptor instead.
func (*PoplarID) Descriptor() ([]byte, []int) {
	return file_poplar_proto_rawDescGZIP(), []int{0}
}

func (x *PoplarID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path      string                            `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ChunkSize int32                             `protobuf:"varint,3,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	Streaming bool                              `protobuf:"varint,4,opt,name=streaming,proto3" json:"streaming,omitempty"`
	Dynamic   bool                              `protobuf:"varint,5,opt,name=dynamic,proto3" json:"dynamic,omitempty"`
	Recorder  CreateOptions_RecorderType        `protobuf:"varint,6,opt,name=recorder,proto3,enum=poplar.CreateOptions_RecorderType" json:"recorder,omitempty"`
	Events    CreateOptions_EventsCollectorType `protobuf:"varint,7,opt,name=events,proto3,enum=poplar.CreateOptions_EventsCollectorType" json:"events,omitempty"`
	Buffered  bool                              `protobuf:"varint,8,opt,name=buffered,proto3" json:"buffered,omitempty"`
}

func (x *CreateOptions) Reset() {
	*x = CreateOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poplar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOptions) ProtoMessage() {}

func (x *CreateOptions) ProtoReflect() protoreflect.Message {
	mi := &file_poplar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOptions.ProtoReflect.Descriptor instead.
func (*CreateOptions) Descriptor() ([]byte, []int) {
	return file_poplar_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOptions) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateOptions) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *CreateOptions) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *CreateOptions) GetDynamic() bool {
	if x != nil {
		return x.Dynamic
	}
	return false
}

func (x *CreateOptions) GetRecorder() CreateOptions_RecorderType {
	if x != nil {
		return x.Recorder
	}
	return CreateOptions_UNKNOWN_RECORDER
}

func (x *CreateOptions) GetEvents() CreateOptions_EventsCollectorType {
	if x != nil {
		return x.Events
	}
	return CreateOptions_UNKNOWN_COLLECTOR
}

func (x *CreateOptions) GetBuffered() bool {
	if x != nil {
		return x.Buffered
	}
	return false
}

type PoplarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status bool   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PoplarResponse) Reset() {
	*x = PoplarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poplar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoplarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoplarResponse) ProtoMessage() {}

func (x *PoplarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poplar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoplarResponse.ProtoReflect.Descriptor instead.
func (*PoplarResponse) Descriptor() ([]byte, []int) {
	return file_poplar_proto_rawDescGZIP(), []int{2}
}

func (x *PoplarResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PoplarResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_poplar_proto protoreflect.FileDescriptor

var file_poplar_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x22, 0x1e, 0x0a, 0x08, 0x50, 0x6f, 0x70, 0x6c, 0x61, 0x72,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xde, 0x05, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x3e, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x70, 0x6f, 0x70, 0x6c, 0x61,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x70, 0x6f, 0x70, 0x6c, 0x61, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x62, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x65, 0x64, 0x22, 0xb5, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x50, 0x45, 0x52, 0x46, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x45, 0x52, 0x46, 0x5f, 0x53,
	0x49, 0x4e, 0x47, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x45, 0x52, 0x46, 0x5f,
	0x31, 0x30, 0x30, 0x4d, 0x53, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x52, 0x46, 0x5f,
	0x31, 0x53, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x48, 0x49, 0x53, 0x54, 0x4f, 0x47, 0x52, 0x41,
	0x4d, 0x5f, 0x53, 0x49, 0x4e, 0x47, 0x4c, 0x45, 0x10, 0x06, 0x12, 0x13, 0x0a, 0x0f, 0x48, 0x49,
	0x53, 0x54, 0x4f, 0x47, 0x52, 0x41, 0x4d, 0x5f, 0x31, 0x30, 0x30, 0x4d, 0x53, 0x10, 0x07, 0x12,
	0x10, 0x0a, 0x0c, 0x48, 0x49, 0x53, 0x54, 0x4f, 0x47, 0x52, 0x41, 0x4d, 0x5f, 0x31, 0x53, 0x10,
	0x08, 0x12, 0x1a, 0x0a, 0x16, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x56, 0x41, 0x4c, 0x5f, 0x53, 0x55,
	0x4d, 0x4d, 0x41, 0x52, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x09, 0x22, 0xf7, 0x01,
	0x0a, 0x13, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x5f, 0x43, 0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x42, 0x41, 0x53, 0x49, 0x43, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x41, 0x53, 0x53, 0x54,
	0x48, 0x52, 0x4f, 0x55, 0x47, 0x48, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x41, 0x4d, 0x50,
	0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x31, 0x30, 0x30, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x41,
	0x4d, 0x50, 0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x31, 0x4b, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x53,
	0x41, 0x4d, 0x50, 0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x31, 0x30, 0x4b, 0x10, 0x05, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x41, 0x4d, 0x50, 0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x31, 0x30, 0x30, 0x4b, 0x10, 0x06,
	0x12, 0x14, 0x0a, 0x10, 0x52, 0x41, 0x4e, 0x44, 0x5f, 0x53, 0x41, 0x4d, 0x50, 0x4c, 0x49, 0x4e,
	0x47, 0x5f, 0x35, 0x30, 0x10, 0x07, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x41, 0x4e, 0x44, 0x5f, 0x53,
	0x41, 0x4d, 0x50, 0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x32, 0x35, 0x10, 0x08, 0x12, 0x14, 0x0a, 0x10,
	0x52, 0x41, 0x4e, 0x44, 0x5f, 0x53, 0x41, 0x4d, 0x50, 0x4c, 0x49, 0x4e, 0x47, 0x5f, 0x31, 0x30,
	0x10, 0x09, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x56, 0x41, 0x4c, 0x5f, 0x31,
	0x30, 0x30, 0x4d, 0x53, 0x10, 0x0a, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x56,
	0x41, 0x4c, 0x5f, 0x31, 0x53, 0x10, 0x0b, 0x22, 0x3c, 0x0a, 0x0e, 0x50, 0x6f, 0x70, 0x6c, 0x61,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_poplar_proto_rawDescOnce sync.Once
	file_poplar_proto_rawDescData = file_poplar_proto_rawDesc
)

func file_poplar_proto_rawDescGZIP() []byte {
	file_poplar_proto_rawDescOnce.Do(func() {
		file_poplar_proto_rawDescData = protoimpl.X.CompressGZIP(file_poplar_proto_rawDescData)
	})
	return file_poplar_proto_rawDescData
}

var file_poplar_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_poplar_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_poplar_proto_goTypes = []interface{}{
	(CreateOptions_RecorderType)(0),        // 0: poplar.CreateOptions.RecorderType
	(CreateOptions_EventsCollectorType)(0), // 1: poplar.CreateOptions.EventsCollectorType
	(*PoplarID)(nil),                       // 2: poplar.PoplarID
	(*CreateOptions)(nil),                  // 3: poplar.CreateOptions
	(*PoplarResponse)(nil),                 // 4: poplar.PoplarResponse
}
var file_poplar_proto_depIdxs = []int32{
	0, // 0: poplar.CreateOptions.recorder:type_name -> poplar.CreateOptions.RecorderType
	1, // 1: poplar.CreateOptions.events:type_name -> poplar.CreateOptions.EventsCollectorType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_poplar_proto_init() }
func file_poplar_proto_init() {
	if File_poplar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_poplar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoplarID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poplar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poplar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoplarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_poplar_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_poplar_proto_goTypes,
		DependencyIndexes: file_poplar_proto_depIdxs,
		EnumInfos:         file_poplar_proto_enumTypes,
		MessageInfos:      file_poplar_proto_msgTypes,
	}.Build()
	File_poplar_proto = out.File
	file_poplar_proto_rawDesc = nil
	file_poplar_proto_goTypes = nil
	file_poplar_proto_depIdxs = nil
}
