// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recorder.proto

package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RecorderID struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecorderID) Reset()         { *m = RecorderID{} }
func (m *RecorderID) String() string { return proto.CompactTextString(m) }
func (*RecorderID) ProtoMessage()    {}
func (*RecorderID) Descriptor() ([]byte, []int) {
	return fileDescriptor_recorder_f6010653bbc04d60, []int{0}
}
func (m *RecorderID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecorderID.Unmarshal(m, b)
}
func (m *RecorderID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecorderID.Marshal(b, m, deterministic)
}
func (dst *RecorderID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecorderID.Merge(dst, src)
}
func (m *RecorderID) XXX_Size() int {
	return xxx_messageInfo_RecorderID.Size(m)
}
func (m *RecorderID) XXX_DiscardUnknown() {
	xxx_messageInfo_RecorderID.DiscardUnknown(m)
}

var xxx_messageInfo_RecorderID proto.InternalMessageInfo

func (m *RecorderID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RecorderInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecorderInfo) Reset()         { *m = RecorderInfo{} }
func (m *RecorderInfo) String() string { return proto.CompactTextString(m) }
func (*RecorderInfo) ProtoMessage()    {}
func (*RecorderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_recorder_f6010653bbc04d60, []int{1}
}
func (m *RecorderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecorderInfo.Unmarshal(m, b)
}
func (m *RecorderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecorderInfo.Marshal(b, m, deterministic)
}
func (dst *RecorderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecorderInfo.Merge(dst, src)
}
func (m *RecorderInfo) XXX_Size() int {
	return xxx_messageInfo_RecorderInfo.Size(m)
}
func (m *RecorderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RecorderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RecorderInfo proto.InternalMessageInfo

func (m *RecorderInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RecorderInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type EventSendTime struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EventSendTime) Reset()         { *m = EventSendTime{} }
func (m *EventSendTime) String() string { return proto.CompactTextString(m) }
func (*EventSendTime) ProtoMessage()    {}
func (*EventSendTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_recorder_f6010653bbc04d60, []int{2}
}
func (m *EventSendTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventSendTime.Unmarshal(m, b)
}
func (m *EventSendTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventSendTime.Marshal(b, m, deterministic)
}
func (dst *EventSendTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSendTime.Merge(dst, src)
}
func (m *EventSendTime) XXX_Size() int {
	return xxx_messageInfo_EventSendTime.Size(m)
}
func (m *EventSendTime) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSendTime.DiscardUnknown(m)
}

var xxx_messageInfo_EventSendTime proto.InternalMessageInfo

func (m *EventSendTime) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventSendTime) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type EventSendInt struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventSendInt) Reset()         { *m = EventSendInt{} }
func (m *EventSendInt) String() string { return proto.CompactTextString(m) }
func (*EventSendInt) ProtoMessage()    {}
func (*EventSendInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_recorder_f6010653bbc04d60, []int{3}
}
func (m *EventSendInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventSendInt.Unmarshal(m, b)
}
func (m *EventSendInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventSendInt.Marshal(b, m, deterministic)
}
func (dst *EventSendInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSendInt.Merge(dst, src)
}
func (m *EventSendInt) XXX_Size() int {
	return xxx_messageInfo_EventSendInt.Size(m)
}
func (m *EventSendInt) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSendInt.DiscardUnknown(m)
}

var xxx_messageInfo_EventSendInt proto.InternalMessageInfo

func (m *EventSendInt) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventSendInt) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type EventSendBool struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                bool     `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventSendBool) Reset()         { *m = EventSendBool{} }
func (m *EventSendBool) String() string { return proto.CompactTextString(m) }
func (*EventSendBool) ProtoMessage()    {}
func (*EventSendBool) Descriptor() ([]byte, []int) {
	return fileDescriptor_recorder_f6010653bbc04d60, []int{4}
}
func (m *EventSendBool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventSendBool.Unmarshal(m, b)
}
func (m *EventSendBool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventSendBool.Marshal(b, m, deterministic)
}
func (dst *EventSendBool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSendBool.Merge(dst, src)
}
func (m *EventSendBool) XXX_Size() int {
	return xxx_messageInfo_EventSendBool.Size(m)
}
func (m *EventSendBool) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSendBool.DiscardUnknown(m)
}

var xxx_messageInfo_EventSendBool proto.InternalMessageInfo

func (m *EventSendBool) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventSendBool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type EventSendDuration struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Time                 *duration.Duration `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EventSendDuration) Reset()         { *m = EventSendDuration{} }
func (m *EventSendDuration) String() string { return proto.CompactTextString(m) }
func (*EventSendDuration) ProtoMessage()    {}
func (*EventSendDuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_recorder_f6010653bbc04d60, []int{5}
}
func (m *EventSendDuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventSendDuration.Unmarshal(m, b)
}
func (m *EventSendDuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventSendDuration.Marshal(b, m, deterministic)
}
func (dst *EventSendDuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSendDuration.Merge(dst, src)
}
func (m *EventSendDuration) XXX_Size() int {
	return xxx_messageInfo_EventSendDuration.Size(m)
}
func (m *EventSendDuration) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSendDuration.DiscardUnknown(m)
}

var xxx_messageInfo_EventSendDuration proto.InternalMessageInfo

func (m *EventSendDuration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventSendDuration) GetTime() *duration.Duration {
	if m != nil {
		return m.Time
	}
	return nil
}

type EventResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResponse) Reset()         { *m = EventResponse{} }
func (m *EventResponse) String() string { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()    {}
func (*EventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recorder_f6010653bbc04d60, []int{6}
}
func (m *EventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResponse.Unmarshal(m, b)
}
func (m *EventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResponse.Marshal(b, m, deterministic)
}
func (dst *EventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResponse.Merge(dst, src)
}
func (m *EventResponse) XXX_Size() int {
	return xxx_messageInfo_EventResponse.Size(m)
}
func (m *EventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventResponse proto.InternalMessageInfo

func (m *EventResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*RecorderID)(nil), "poplar.RecorderID")
	proto.RegisterType((*RecorderInfo)(nil), "poplar.RecorderInfo")
	proto.RegisterType((*EventSendTime)(nil), "poplar.EventSendTime")
	proto.RegisterType((*EventSendInt)(nil), "poplar.EventSendInt")
	proto.RegisterType((*EventSendBool)(nil), "poplar.EventSendBool")
	proto.RegisterType((*EventSendDuration)(nil), "poplar.EventSendDuration")
	proto.RegisterType((*EventResponse)(nil), "poplar.EventResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PoplarMetricsRecorderClient is the client API for PoplarMetricsRecorder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PoplarMetricsRecorderClient interface {
	CreateRecorder(ctx context.Context, in *RecorderID, opts ...grpc.CallOption) (*RecorderInfo, error)
	CloseRecorder(ctx context.Context, in *RecorderID, opts ...grpc.CallOption) (*RecorderInfo, error)
	// Event Lifecycle methods
	BeginEvent(ctx context.Context, in *RecorderID, opts ...grpc.CallOption) (*EventResponse, error)
	ResetRecorder(ctx context.Context, in *RecorderID, opts ...grpc.CallOption) (*EventResponse, error)
	End(ctx context.Context, in *EventSendDuration, opts ...grpc.CallOption) (*EventResponse, error)
	// Timers
	SetTime(ctx context.Context, in *EventSendTime, opts ...grpc.CallOption) (*EventResponse, error)
	SetDuration(ctx context.Context, in *EventSendDuration, opts ...grpc.CallOption) (*EventResponse, error)
	SetTotalDuration(ctx context.Context, in *EventSendDuration, opts ...grpc.CallOption) (*EventResponse, error)
	// Guages
	SetState(ctx context.Context, in *EventSendInt, opts ...grpc.CallOption) (*EventResponse, error)
	SetWorkers(ctx context.Context, in *EventSendInt, opts ...grpc.CallOption) (*EventResponse, error)
	SetBool(ctx context.Context, in *EventSendBool, opts ...grpc.CallOption) (*EventResponse, error)
	// Counters
	IncOps(ctx context.Context, in *EventSendInt, opts ...grpc.CallOption) (*EventResponse, error)
	IncSize(ctx context.Context, in *EventSendInt, opts ...grpc.CallOption) (*EventResponse, error)
	IncError(ctx context.Context, in *EventSendInt, opts ...grpc.CallOption) (*EventResponse, error)
	IncIterations(ctx context.Context, in *EventSendInt, opts ...grpc.CallOption) (*EventResponse, error)
}

type poplarMetricsRecorderClient struct {
	cc *grpc.ClientConn
}

func NewPoplarMetricsRecorderClient(cc *grpc.ClientConn) PoplarMetricsRecorderClient {
	return &poplarMetricsRecorderClient{cc}
}

func (c *poplarMetricsRecorderClient) CreateRecorder(ctx context.Context, in *RecorderID, opts ...grpc.CallOption) (*RecorderInfo, error) {
	out := new(RecorderInfo)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/CreateRecorder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) CloseRecorder(ctx context.Context, in *RecorderID, opts ...grpc.CallOption) (*RecorderInfo, error) {
	out := new(RecorderInfo)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/CloseRecorder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) BeginEvent(ctx context.Context, in *RecorderID, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/BeginEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) ResetRecorder(ctx context.Context, in *RecorderID, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/ResetRecorder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) End(ctx context.Context, in *EventSendDuration, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/End", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) SetTime(ctx context.Context, in *EventSendTime, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/SetTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) SetDuration(ctx context.Context, in *EventSendDuration, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/SetDuration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) SetTotalDuration(ctx context.Context, in *EventSendDuration, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/SetTotalDuration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) SetState(ctx context.Context, in *EventSendInt, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/SetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) SetWorkers(ctx context.Context, in *EventSendInt, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/SetWorkers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) SetBool(ctx context.Context, in *EventSendBool, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/SetBool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) IncOps(ctx context.Context, in *EventSendInt, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/IncOps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) IncSize(ctx context.Context, in *EventSendInt, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/IncSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) IncError(ctx context.Context, in *EventSendInt, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/IncError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poplarMetricsRecorderClient) IncIterations(ctx context.Context, in *EventSendInt, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, "/poplar.PoplarMetricsRecorder/IncIterations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoplarMetricsRecorderServer is the server API for PoplarMetricsRecorder service.
type PoplarMetricsRecorderServer interface {
	CreateRecorder(context.Context, *RecorderID) (*RecorderInfo, error)
	CloseRecorder(context.Context, *RecorderID) (*RecorderInfo, error)
	// Event Lifecycle methods
	BeginEvent(context.Context, *RecorderID) (*EventResponse, error)
	ResetRecorder(context.Context, *RecorderID) (*EventResponse, error)
	End(context.Context, *EventSendDuration) (*EventResponse, error)
	// Timers
	SetTime(context.Context, *EventSendTime) (*EventResponse, error)
	SetDuration(context.Context, *EventSendDuration) (*EventResponse, error)
	SetTotalDuration(context.Context, *EventSendDuration) (*EventResponse, error)
	// Guages
	SetState(context.Context, *EventSendInt) (*EventResponse, error)
	SetWorkers(context.Context, *EventSendInt) (*EventResponse, error)
	SetBool(context.Context, *EventSendBool) (*EventResponse, error)
	// Counters
	IncOps(context.Context, *EventSendInt) (*EventResponse, error)
	IncSize(context.Context, *EventSendInt) (*EventResponse, error)
	IncError(context.Context, *EventSendInt) (*EventResponse, error)
	IncIterations(context.Context, *EventSendInt) (*EventResponse, error)
}

func RegisterPoplarMetricsRecorderServer(s *grpc.Server, srv PoplarMetricsRecorderServer) {
	s.RegisterService(&_PoplarMetricsRecorder_serviceDesc, srv)
}

func _PoplarMetricsRecorder_CreateRecorder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecorderID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).CreateRecorder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/CreateRecorder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).CreateRecorder(ctx, req.(*RecorderID))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_CloseRecorder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecorderID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).CloseRecorder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/CloseRecorder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).CloseRecorder(ctx, req.(*RecorderID))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_BeginEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecorderID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).BeginEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/BeginEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).BeginEvent(ctx, req.(*RecorderID))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_ResetRecorder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecorderID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).ResetRecorder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/ResetRecorder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).ResetRecorder(ctx, req.(*RecorderID))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_End_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventSendDuration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).End(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/End",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).End(ctx, req.(*EventSendDuration))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_SetTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventSendTime)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).SetTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/SetTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).SetTime(ctx, req.(*EventSendTime))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_SetDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventSendDuration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).SetDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/SetDuration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).SetDuration(ctx, req.(*EventSendDuration))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_SetTotalDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventSendDuration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).SetTotalDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/SetTotalDuration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).SetTotalDuration(ctx, req.(*EventSendDuration))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventSendInt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/SetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).SetState(ctx, req.(*EventSendInt))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_SetWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventSendInt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).SetWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/SetWorkers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).SetWorkers(ctx, req.(*EventSendInt))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_SetBool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventSendBool)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).SetBool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/SetBool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).SetBool(ctx, req.(*EventSendBool))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_IncOps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventSendInt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).IncOps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/IncOps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).IncOps(ctx, req.(*EventSendInt))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_IncSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventSendInt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).IncSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/IncSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).IncSize(ctx, req.(*EventSendInt))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_IncError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventSendInt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).IncError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/IncError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).IncError(ctx, req.(*EventSendInt))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoplarMetricsRecorder_IncIterations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventSendInt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoplarMetricsRecorderServer).IncIterations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poplar.PoplarMetricsRecorder/IncIterations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoplarMetricsRecorderServer).IncIterations(ctx, req.(*EventSendInt))
	}
	return interceptor(ctx, in, info, handler)
}

var _PoplarMetricsRecorder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "poplar.PoplarMetricsRecorder",
	HandlerType: (*PoplarMetricsRecorderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRecorder",
			Handler:    _PoplarMetricsRecorder_CreateRecorder_Handler,
		},
		{
			MethodName: "CloseRecorder",
			Handler:    _PoplarMetricsRecorder_CloseRecorder_Handler,
		},
		{
			MethodName: "BeginEvent",
			Handler:    _PoplarMetricsRecorder_BeginEvent_Handler,
		},
		{
			MethodName: "ResetRecorder",
			Handler:    _PoplarMetricsRecorder_ResetRecorder_Handler,
		},
		{
			MethodName: "End",
			Handler:    _PoplarMetricsRecorder_End_Handler,
		},
		{
			MethodName: "SetTime",
			Handler:    _PoplarMetricsRecorder_SetTime_Handler,
		},
		{
			MethodName: "SetDuration",
			Handler:    _PoplarMetricsRecorder_SetDuration_Handler,
		},
		{
			MethodName: "SetTotalDuration",
			Handler:    _PoplarMetricsRecorder_SetTotalDuration_Handler,
		},
		{
			MethodName: "SetState",
			Handler:    _PoplarMetricsRecorder_SetState_Handler,
		},
		{
			MethodName: "SetWorkers",
			Handler:    _PoplarMetricsRecorder_SetWorkers_Handler,
		},
		{
			MethodName: "SetBool",
			Handler:    _PoplarMetricsRecorder_SetBool_Handler,
		},
		{
			MethodName: "IncOps",
			Handler:    _PoplarMetricsRecorder_IncOps_Handler,
		},
		{
			MethodName: "IncSize",
			Handler:    _PoplarMetricsRecorder_IncSize_Handler,
		},
		{
			MethodName: "IncError",
			Handler:    _PoplarMetricsRecorder_IncError_Handler,
		},
		{
			MethodName: "IncIterations",
			Handler:    _PoplarMetricsRecorder_IncIterations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recorder.proto",
}

func init() { proto.RegisterFile("recorder.proto", fileDescriptor_recorder_f6010653bbc04d60) }

var fileDescriptor_recorder_f6010653bbc04d60 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x55, 0x5a, 0x92, 0x30, 0x6d, 0x2a, 0xb0, 0x12, 0xd4, 0xe6, 0x00, 0x95, 0x4f, 0x5c,
	0x70, 0xa5, 0x22, 0x1a, 0x52, 0x90, 0x90, 0xd2, 0xe4, 0xe0, 0x03, 0x02, 0xd9, 0x15, 0x48, 0xdc,
	0xb6, 0xce, 0x34, 0x58, 0x38, 0xb3, 0xd6, 0xee, 0xb8, 0x07, 0x5e, 0x82, 0x57, 0x46, 0xde, 0xb5,
	0x4d, 0x83, 0x6d, 0x90, 0xe9, 0xcd, 0xfe, 0x3c, 0xbf, 0x99, 0x6f, 0xfe, 0x18, 0x0e, 0x15, 0x46,
	0x52, 0xad, 0x50, 0x79, 0xa9, 0x92, 0x2c, 0x9d, 0x5e, 0x2a, 0xd3, 0x44, 0xa8, 0xc9, 0xf3, 0xb5,
	0x94, 0xeb, 0x04, 0x4f, 0x8d, 0x7a, 0x9d, 0xdd, 0x9c, 0x72, 0xbc, 0x41, 0xcd, 0x62, 0x93, 0xda,
	0xc0, 0xc9, 0xb3, 0x3f, 0x03, 0x56, 0x99, 0x12, 0x1c, 0x4b, 0xb2, 0xdf, 0xdd, 0x13, 0x80, 0xa0,
	0x48, 0xed, 0x2f, 0x1c, 0x07, 0xf6, 0x48, 0x6c, 0xf0, 0x68, 0xe7, 0x64, 0xe7, 0xc5, 0xa3, 0xc0,
	0x3c, 0xbb, 0xe7, 0x70, 0x50, 0x45, 0xd0, 0x8d, 0x6c, 0x8a, 0xc9, 0xb5, 0x54, 0xf0, 0xb7, 0xa3,
	0x07, 0x56, 0xcb, 0x9f, 0xdd, 0x10, 0x86, 0xcb, 0x5b, 0x24, 0x0e, 0x91, 0x56, 0x57, 0xb1, 0x0d,
	0xaa, 0x81, 0x1e, 0xec, 0xe5, 0x8e, 0x0d, 0xb8, 0x7f, 0x36, 0xf1, 0xac, 0x5b, 0xaf, 0x74, 0xeb,
	0x5d, 0x95, 0xed, 0x04, 0x26, 0xce, 0x7d, 0x03, 0x07, 0x55, 0x52, 0x9f, 0xb8, 0x31, 0xe7, 0x08,
	0x1e, 0xde, 0x8a, 0x24, 0xb3, 0x49, 0x77, 0x03, 0xfb, 0xe2, 0xce, 0xee, 0xd8, 0x99, 0x4b, 0x99,
	0xfc, 0x1b, 0x1d, 0x94, 0xe8, 0x67, 0x78, 0x52, 0xa1, 0x8b, 0x62, 0x7c, 0x8d, 0xf8, 0xcb, 0xad,
	0x6e, 0x8e, 0x6b, 0xdd, 0x94, 0x70, 0xd1, 0xcc, 0xdb, 0xc2, 0x52, 0x80, 0x3a, 0x95, 0xa4, 0x9b,
	0x27, 0xf4, 0x14, 0x7a, 0x9a, 0x05, 0x67, 0xba, 0xf0, 0x54, 0xbc, 0x9d, 0xfd, 0xec, 0xc3, 0xf8,
	0x93, 0x39, 0x82, 0x0f, 0xc8, 0x2a, 0x8e, 0x74, 0xb9, 0x24, 0xe7, 0x02, 0x0e, 0x2f, 0x15, 0x0a,
	0xc6, 0x4a, 0x71, 0x3c, 0x7b, 0x2e, 0xde, 0xef, 0x55, 0x4f, 0x46, 0x35, 0x2d, 0x5f, 0xee, 0x0c,
	0x86, 0x97, 0x89, 0xd4, 0xff, 0x83, 0x4e, 0x01, 0xe6, 0xb8, 0x8e, 0xc9, 0xb4, 0xd4, 0xc8, 0x8d,
	0x4b, 0x6d, 0xbb, 0xeb, 0x0b, 0x18, 0x06, 0xa8, 0x91, 0xff, 0x5a, 0xb3, 0x85, 0x9d, 0xc2, 0xee,
	0x92, 0x56, 0xce, 0xf1, 0xd6, 0xd7, 0xbb, 0x7b, 0x6a, 0x07, 0xfb, 0x21, 0xb2, 0xb9, 0xcb, 0x71,
	0x0d, 0xce, 0xe5, 0x36, 0xf0, 0x3d, 0xec, 0x87, 0xc8, 0xd5, 0x19, 0x74, 0xaf, 0xbc, 0x80, 0xc7,
	0x79, 0x65, 0xc9, 0x22, 0xb9, 0x47, 0x96, 0x29, 0x0c, 0x42, 0xe4, 0x90, 0x05, 0xa3, 0x33, 0xaa,
	0xd1, 0x3e, 0x71, 0x1b, 0x38, 0x03, 0x08, 0x91, 0xbf, 0x48, 0xf5, 0x1d, 0x95, 0xee, 0x86, 0xda,
	0x99, 0x99, 0x9f, 0xa7, 0x3e, 0xb3, 0x5c, 0x6e, 0x03, 0x5f, 0x43, 0xcf, 0xa7, 0xe8, 0x63, 0xda,
	0xb1, 0xde, 0x39, 0xf4, 0x7d, 0x8a, 0xc2, 0xf8, 0x07, 0x76, 0xf5, 0x39, 0xf0, 0x29, 0x5a, 0x2a,
	0x25, 0x55, 0x37, 0xf0, 0x1d, 0x0c, 0x7d, 0x8a, 0x7c, 0x46, 0x3b, 0xfb, 0x6e, 0x76, 0xe7, 0xf0,
	0x75, 0x10, 0x13, 0xa3, 0x22, 0x91, 0x5c, 0xf7, 0xcc, 0x3f, 0xff, 0xea, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf7, 0xf0, 0x77, 0x52, 0xb8, 0x05, 0x00, 0x00,
}
